name: Pull request checks

on:
  pull_request:
    branches:
      - '**'

jobs:
  build:

    strategy:
      matrix:
        os: [windows-latest]
        dotnet: [6.0.203]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.203
    - name: Restore tools
      run: dotnet tool restore
    - name: Restore projects
      run: dotnet restore FSharp.Compiler.Service\FSharp.Compiler.Service.fsproj
    - name: Checkout fsharp master
      run: git clone https://github.com/dotnet/fsharp --depth 1 fsharp -b main
    - name: Build fsharp master (turn of CI build status)
      run: cd fsharp && eng\CIBuild.cmd  -noVisualStudio
    - name: Run fsdocs
      run: dotnet fsdocs build --sourcefolder fsharp --input fsharp/docs
