name: Pull request checks

on:
  pull_request:
    branches:
      - '**'

env:
  FSHARP_DIR: fsharp

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Checkout fsharp main
        uses: actions/checkout@v3
        with:
          repository: dotnet/fsharp
          path: ${{ env.FSHARP_DIR }}
          ref: main
      - name: Setup .NET for FSharp
        uses: actions/setup-dotnet@v3
        with:
          global-json-file: ${{ env.FSHARP_DIR }}/global.json
      - name: Restore tools
        run: dotnet tool restore
      - name: Restore FSharp.Compiler.Service.fsproj
        run: dotnet restore FSharp.Compiler.Service/FSharp.Compiler.Service.fsproj

      - name: Build FCS
        run: dotnet build src/Compiler/FSharp.Compiler.Service.fsproj /p:BUILDING_USING_DOTNET=true
        working-directory: ${{ env.FSHARP_DIR }}

      - name: Run fsdocs
        env:
              # allow roll forward to latest major version - this would happen for us if we invoked the fsdocs tool instead of invoking the binary directly
              DOTNET_ROLL_FORWARD: "LatestMajor"
              # need previews because .NET 8 is what's being used at runtime
              DOTNET_ROLL_FORWARD_TO_PRERELEASE: "1"
        run: dotnet fsdocs build --sourcefolder fsharp --input fsharp/docs
